server:
    servlet:
        encoding:
            charset: UTF-8
            enabled: true
            force: true

jpmc:
    providers:
        - name: provider1
          url: https://provider1.com/v1/api/account/validate
        - name: provider2
          url: https://provider2.com/v2/api/account/validate